### ISSUE TITLE
PR to add eslint-plugin-flowtype-errors

### ISSUE THREAD

**Issue by amilajack** [danillouz/flowtype-example#1]
Wondering if a PR to add [eslint-plugin-flowtype-errors](https://github.com/amilajack/eslint-plugin-flowtype-errors) to the docs would be welcome.

Here's a demo:
![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

**Comment by danillouz** [comment]
Sure no problem
